### ISSUE TITLE
bug: renaming file action iterates over dependencies

### ISSUE THREAD

**Issue by joneugster** [DenisGorbachev/vscode-lean4-code-actions#21]
When the "updating imports" action triggers, it also looks through any files in the dependencies, which is superfluous and a huge slowdown.

## Reproduction

1. Create a new project depending on Mathlib: `lake new testproject math`
2. Go into the project (`cd testproject`)
3. build it (`lake exe cache get` and `lake build`). Maybe optional.
4. Open VSCode with the extension enabled. (`code .`)
5. Note how there are only 2-3 .lean files present: `Testproject.lean`, `Testproject/Basic.lean` and potentially a `Main.lean`.
6. Rename any file in the project, for example `Testproject/Basic.lean` to `Testproject/Basic2.lean` 
7. The code action triggers and goes through about 5000 files checking for updating imports.

![lean-code-action-bug](https://github.com/DenisGorbachev/vscode-lean4-code-actions/assets/9141564/4ab0a230-2a6b-478e-a993-ab5564637f12)

## Expected behavior

The extension should ignore all dependencies when "updating imports" as they must not be modified anyways.

These are mostly files in `.lake/` but they might in rare circumstances also be somewhere else (outside the root folder) if one imports a local dependency in `lakefile.lean`.

Therefore it would be best to only search for `.lean` files which are inside the projects folder excluding `.lake/`

**Comment by DenisGorbachev** [comment]
Hi @joneugster, thank you for a thorough reproduction! 

However, I'm not working on this extension anymore. Will gladly accept a PR :)

**Comment by joneugster** [comment]
I realised it might be a single line fix #22 : they moved `lake-packages` into `.lake` some year ago

**Comment by DenisGorbachev** [comment]
@joneugster A new version 1.1.32 is being published (under review right now, check [version history](https://marketplace.visualstudio.com/items?itemName=denis-gorbachev.lean4-code-actions&ssr=false#version-history)).

Could you please check if the fix works for you? (when the new version appears on VSCode Marketplace)

**Comment by joneugster** [comment]
I kinda forgot about this, but I checked the link and the newest version still says 1.1.31, @DenisGorbachev

**Comment by DenisGorbachev** [comment]
Published 1.1.32 now, not sure why the first publish didn't go through

**Comment by joneugster** [comment]
Looks good, thank you!
